2013-12-20 04:01:32 [ main:0 ] - [ DEBUG ] 111
 2013-12-20 04:01:32 [ main:16 ] - [ INFO ] 222
 2013-12-20 04:01:32 [ main:16 ] - [ WARN ] 333
 2013-12-20 04:01:32 [ main:16 ] - [ ERROR ] 444
 2013-12-20 04:01:32 [ main:16 ] - [ FATAL ] 555
 2013-12-20 04:02:25 [ main:0 ] - [ DEBUG ] 111
 2013-12-20 04:02:25 [ main:0 ] - [ INFO ] 222
 2013-12-20 04:02:25 [ main:0 ] - [ WARN ] 333
 2013-12-20 04:02:25 [ main:0 ] - [ ERROR ] 444
 2013-12-20 04:02:25 [ main:0 ] - [ FATAL ] 555
 2013-12-20 04:02:48 [ main:0 ] - [ DEBUG ] 111
 2013-12-20 04:02:48 [ main:0 ] - [ INFO ] 222
 2013-12-20 04:02:48 [ main:0 ] - [ WARN ] 333
 2013-12-20 04:02:48 [ main:0 ] - [ ERROR ] 444
 2013-12-20 04:02:48 [ main:0 ] - [ FATAL ] 555
 [2017-02-20 18:23:31,530][INFO, (NettyServer.java:46).run] websocket_text server started at port 8080.
[2017-02-20 18:23:55,166][WARN, (HandlerDispatcher.java:144).handMessageQueue] 指令 [999]找不到
[2017-02-20 18:26:20,683][INFO, (NettyServer.java:46).run] websocket_text server started at port 8080.
[2017-02-20 18:27:32,895][WARN, (HandlerDispatcher.java:144).handMessageQueue] 指令 [999]找不到
[2017-02-20 18:29:08,171][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-21 12:33:25,313][INFO, (NettyServer.java:46).run] websocket_text server started at port 8080.
[2017-02-21 12:37:33,522][ERROR, (InitHandler.java:24).execute] Are you ok?
[2017-02-21 12:38:16,290][ERROR, (InitHandler.java:24).execute] Are you ok?
[2017-02-21 12:38:31,344][INFO, (NettyServer.java:46).run] websocket_text server started at port 8080.
[2017-02-21 12:38:39,652][ERROR, (InitHandler.java:24).execute] Are you ok?
[2017-02-21 12:38:45,563][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-21 12:39:36,763][INFO, (ClientInitHandler.java:24).channelActive] ClientInitHandler.channelActive
[2017-02-21 12:40:00,969][INFO, (ClientInitHandler.java:24).channelActive] ClientInitHandler.channelActive
[2017-02-21 12:40:00,997][INFO, (BusinessHandler.java:22).channelRead] BusinessHandler read msg from client :name:guoxy sex:girl age:4
[2017-02-21 12:41:28,017][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 12:41:28,131][INFO, (BusinessHandler.java:19).channelRead] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 12:41:46,249][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-21 12:42:23,640][INFO, (StringDecoder.java:23).channelRead] StringDecoder : msg's type is class io.netty.handler.codec.http.DefaultHttpRequest
[2017-02-21 12:42:23,667][INFO, (StringDecoder.java:23).channelRead] StringDecoder : msg's type is class io.netty.handler.codec.http.DefaultLastHttpContent
[2017-02-21 12:42:23,667][INFO, (StringDecoder.java:35).channelRead] StringDecoder : change httpcontent to string 
[2017-02-21 12:42:23,667][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : Are you ok?
[2017-02-21 12:42:23,667][INFO, (StringEncoder.java:26).write] StringEncoder response to client.
[2017-02-21 13:34:48,255][INFO, (StringDecoder.java:23).channelRead] StringDecoder : msg's type is class io.netty.handler.codec.http.DefaultHttpRequest
[2017-02-21 13:34:48,315][INFO, (StringDecoder.java:23).channelRead] StringDecoder : msg's type is class io.netty.handler.codec.http.DefaultLastHttpContent
[2017-02-21 13:34:48,315][INFO, (StringDecoder.java:35).channelRead] StringDecoder : change httpcontent to string 
[2017-02-21 13:34:48,316][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : Are you ok?
[2017-02-21 13:34:48,316][INFO, (StringEncoder.java:26).write] StringEncoder response to client.
[2017-02-21 13:38:02,620][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : ssssssssss
[2017-02-21 13:38:06,119][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:38:06,127][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : ssssss
[2017-02-21 13:38:06,128][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : sss
[2017-02-21 13:38:11,440][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:38:11,441][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : sssssssss
[2017-02-21 13:38:21,089][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:38:23,026][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:38:24,028][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:38:26,145][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:38:27,172][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:38:29,658][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:38:56,292][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:38:58,289][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:39:08,529][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:39:13,852][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:39:15,393][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:39:18,327][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 13:39:19,687][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : s
[2017-02-21 16:12:06,301][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 16:12:06,464][INFO, (BusinessHandler.java:19).channelRead] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 16:13:39,873][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 16:13:39,906][INFO, (BusinessHandler.java:19).channelRead] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 16:14:04,909][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-21 16:15:08,724][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 16:15:09,289][INFO, (BusinessHandler.java:19).channelRead] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 16:15:52,979][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-21 16:16:19,788][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 16:16:19,907][INFO, (BusinessHandler.java:19).channelRead] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 16:19:31,506][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-21 16:20:13,125][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 16:20:13,690][INFO, (BusinessHandler.java:19).channelRead] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 16:21:24,046][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 16:21:24,088][INFO, (BusinessHandler.java:19).channelRead] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 16:29:14,703][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 16:29:36,763][INFO, (BusinessHandler.java:19).channelRead] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 16:34:37,020][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 16:34:37,148][INFO, (BusinessHandler.java:19).channelRead] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 16:34:37,154][INFO, (ClientInitHandler.java:27).channelRead] BusinessHandler read msg from server :name:guowl sex:man age:30
[2017-02-21 16:43:09,728][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 16:43:09,894][INFO, (DispatcherHandler.java:38).run] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 16:43:09,903][INFO, (ClientInitHandler.java:27).channelRead] BusinessHandler read msg from server :name:guowl sex:man age:30
[2017-02-21 16:43:19,660][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-21 16:43:19,683][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:199)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:46)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:77)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:299)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:827)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:544)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:318)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.netty.Util.ByteObjConverter.ByteToObject(ByteObjConverter.java:37)
	at com.netty.test5.ser.PersonDecoder.decode(PersonDecoder.java:17)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeLast(ByteToMessageDecoder.java:283)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:194)
	... 9 more
[2017-02-21 16:43:38,717][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 16:43:38,850][INFO, (DispatcherHandler.java:38).run] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 16:43:38,858][INFO, (ClientInitHandler.java:27).channelRead] BusinessHandler read msg from server :name:guowl sex:man age:30
[2017-02-21 16:43:43,582][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-21 16:43:43,603][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:199)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:46)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:77)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:299)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:827)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:544)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:318)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.netty.Util.ByteObjConverter.ByteToObject(ByteObjConverter.java:37)
	at com.netty.test5.ser.PersonDecoder.decode(PersonDecoder.java:17)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeLast(ByteToMessageDecoder.java:283)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:194)
	... 9 more
[2017-02-21 17:03:02,520][INFO, (StringDecoder.java:23).channelRead] StringDecoder : msg's type is class io.netty.handler.codec.http.DefaultHttpRequest
[2017-02-21 17:03:02,543][INFO, (StringDecoder.java:23).channelRead] StringDecoder : msg's type is class io.netty.handler.codec.http.DefaultLastHttpContent
[2017-02-21 17:03:02,543][INFO, (StringDecoder.java:35).channelRead] StringDecoder : change httpcontent to string 
[2017-02-21 17:03:02,544][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : Are you ok?
[2017-02-21 17:03:02,544][INFO, (StringEncoder.java:29).write] StringEncoder response to client.
[2017-02-21 17:07:02,109][INFO, (StringDecoder.java:23).channelRead] StringDecoder : msg's type is class io.netty.handler.codec.http.DefaultHttpRequest
[2017-02-21 17:07:02,132][INFO, (StringDecoder.java:23).channelRead] StringDecoder : msg's type is class io.netty.handler.codec.http.DefaultLastHttpContent
[2017-02-21 17:07:02,132][INFO, (StringDecoder.java:35).channelRead] StringDecoder : change httpcontent to string 
[2017-02-21 17:07:02,133][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : Are you ok?
[2017-02-21 17:07:02,133][INFO, (StringEncoder.java:29).write] StringEncoder response to client.
[2017-02-21 17:07:28,209][INFO, (StringDecoder.java:23).channelRead] StringDecoder : msg's type is class io.netty.handler.codec.http.DefaultHttpRequest
[2017-02-21 17:07:28,210][INFO, (StringDecoder.java:23).channelRead] StringDecoder : msg's type is class io.netty.handler.codec.http.DefaultLastHttpContent
[2017-02-21 17:07:28,210][INFO, (StringDecoder.java:35).channelRead] StringDecoder : change httpcontent to string 
[2017-02-21 17:07:28,211][INFO, (BusinessHandler.java:15).channelRead] BusinessHandler read msg from client :client said : Are you ok?
[2017-02-21 17:07:28,211][INFO, (StringEncoder.java:29).write] StringEncoder response to client.
[2017-02-21 17:10:16,176][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-21 17:10:31,716][INFO, (DispatcherHandler.java:38).run] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-21 17:10:31,784][INFO, (ClientInitHandler.java:27).channelRead] BusinessHandler read msg from server :name:guowl sex:man age:30
[2017-02-21 17:10:54,617][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-21 17:10:55,139][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:199)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:46)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:77)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:299)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:827)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:544)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:318)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.netty.Util.ByteObjConverter.ByteToObject(ByteObjConverter.java:37)
	at com.netty.test5.ser.PersonDecoder.decode(PersonDecoder.java:17)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeLast(ByteToMessageDecoder.java:283)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:194)
	... 9 more
[2017-02-22 13:55:08,235][INFO, (HelloClientIntHandler.java:27).channelActive] HelloClientIntHandler.channelActive
[2017-02-22 13:55:08,398][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.close(ChannelOutboundBuffer.java:533)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:537)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:76)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 13:58:06,666][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 13:58:06,681][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.close(ChannelOutboundBuffer.java:533)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:537)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:76)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:92)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:152)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 14:07:17,858][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.close(ChannelOutboundBuffer.java:533)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:537)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:76)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 14:14:37,010][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:312)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:266)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:652)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:271)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:621)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.flush(DefaultChannelPipeline.java:1065)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at io.netty.channel.ChannelHandlerAdapter.flush(ChannelHandlerAdapter.java:234)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at com.netty.test13.netty.TimeServerHandler3.channelReadComplete(TimeServerHandler3.java:38)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:82)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:152)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelReadComplete(DefaultChannelHandlerContext.java:327)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:852)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:144)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 14:36:34,627][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:312)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:266)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:652)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:271)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:621)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.flush(DefaultChannelPipeline.java:1065)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at io.netty.channel.ChannelHandlerAdapter.flush(ChannelHandlerAdapter.java:234)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at com.netty.test13.netty.TimeServerHandler3.channelReadComplete(TimeServerHandler3.java:38)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:82)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:152)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelReadComplete(DefaultChannelHandlerContext.java:327)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:852)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:144)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 14:43:59,147][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:312)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:266)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:652)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:271)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:621)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.flush(DefaultChannelPipeline.java:1065)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at io.netty.channel.ChannelHandlerAdapter.flush(ChannelHandlerAdapter.java:234)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at com.netty.test13.netty.TimeServerHandler3.channelReadComplete(TimeServerHandler3.java:38)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:82)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:152)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelReadComplete(DefaultChannelHandlerContext.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelReadComplete(ByteToMessageDecoder.java:183)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:82)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:152)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelReadComplete(DefaultChannelHandlerContext.java:327)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:852)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:144)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 14:54:39,001][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:312)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:266)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:652)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:271)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:621)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.flush(DefaultChannelPipeline.java:1065)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at io.netty.channel.ChannelHandlerAdapter.flush(ChannelHandlerAdapter.java:234)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at com.netty.test13.netty.TimeServerHandler3.channelReadComplete(TimeServerHandler3.java:37)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:82)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:152)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelReadComplete(DefaultChannelHandlerContext.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelReadComplete(ByteToMessageDecoder.java:183)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:82)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:152)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelReadComplete(DefaultChannelHandlerContext.java:327)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:852)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:144)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:01:48,564][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.close(ChannelOutboundBuffer.java:533)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:537)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:76)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:04:42,288][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:312)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:266)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:652)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:271)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:621)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.flush(DefaultChannelPipeline.java:1065)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at io.netty.channel.ChannelHandlerAdapter.flush(ChannelHandlerAdapter.java:234)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at com.netty.test13.netty.TimeServerHandler3.channelReadComplete(TimeServerHandler3.java:34)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:82)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:152)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelReadComplete(DefaultChannelHandlerContext.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelReadComplete(ByteToMessageDecoder.java:183)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:82)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:152)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelReadComplete(DefaultChannelHandlerContext.java:327)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:852)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:144)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:05:41,951][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.close(ChannelOutboundBuffer.java:533)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:537)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:76)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:07:07,792][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:312)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:266)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:652)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:271)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:621)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.flush(DefaultChannelPipeline.java:1065)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at io.netty.channel.ChannelHandlerAdapter.flush(ChannelHandlerAdapter.java:234)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:432)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:438)
	at com.netty.test13.netty.TimeServerHandler3.channelActive(TimeServerHandler3.java:29)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelActiveNow(ChannelHandlerInvokerUtil.java:38)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelActive(DefaultChannelHandlerInvoker.java:63)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelActive(DefaultChannelHandlerContext.java:292)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:816)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:369)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:318)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:13:39,750][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
	at com.netty.test13.netty.TimeClientHandler3.channelActive(TimeClientHandler3.java:12)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelActiveNow(ChannelHandlerInvokerUtil.java:38)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelActive(DefaultChannelHandlerInvoker.java:63)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelActive(DefaultChannelHandlerContext.java:292)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:816)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:222)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:242)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:502)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:13:39,764][WARN, (Slf4JLogger.java:151).warn] Failed to release a message.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:115)
	at io.netty.buffer.WrappedByteBuf.release(WrappedByteBuf.java:819)
	at io.netty.buffer.SimpleLeakAwareByteBuf.release(SimpleLeakAwareByteBuf.java:34)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:68)
	at io.netty.channel.ChannelOutboundBuffer.safeRelease(ChannelOutboundBuffer.java:559)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:312)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:266)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:652)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:271)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:621)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.flush(DefaultChannelPipeline.java:1065)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:422)
	at io.netty.channel.ChannelHandlerAdapter.flush(ChannelHandlerAdapter.java:234)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:148)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:306)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:432)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:438)
	at com.netty.test13.netty.TimeServerHandler3.channelActive(TimeServerHandler3.java:29)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelActiveNow(ChannelHandlerInvokerUtil.java:38)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelActive(DefaultChannelHandlerInvoker.java:63)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelActive(DefaultChannelHandlerContext.java:292)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:816)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:369)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:318)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:15:07,331][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
	at com.netty.test13.netty.TimeClientHandler3.channelActive(TimeClientHandler3.java:12)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelActiveNow(ChannelHandlerInvokerUtil.java:38)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelActive(DefaultChannelHandlerInvoker.java:63)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelActive(DefaultChannelHandlerContext.java:292)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:816)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:222)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:242)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:502)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:42:44,532][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:43:43,895][INFO, (ClientInitHandler.java:24).channelActive] ClientInitHandler.channelActive
[2017-02-22 15:43:43,943][INFO, (BusinessHandler.java:22).channelRead] BusinessHandler read msg from client :name:guoxy sex:girl age:4
[2017-02-22 15:44:08,628][INFO, (ClientInitHandler.java:24).channelActive] ClientInitHandler.channelActive
[2017-02-22 15:44:23,740][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:44:46,298][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-22 15:44:46,367][INFO, (DispatcherHandler.java:38).run] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-22 15:44:46,376][INFO, (ClientInitHandler.java:27).channelRead] BusinessHandler read msg from server :name:guowl sex:man age:30
[2017-02-22 15:45:45,009][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:45:45,023][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:199)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:46)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:77)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:299)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:827)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:544)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:318)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.netty.Util.ByteObjConverter.ByteToObject(ByteObjConverter.java:37)
	at com.netty.test5.ser.PersonDecoder.decode(PersonDecoder.java:17)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeLast(ByteToMessageDecoder.java:283)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:194)
	... 9 more
[2017-02-22 15:45:58,437][INFO, (ClientInitHandler.java:15).channelActive] HelloClientIntHandler.channelActive
[2017-02-22 15:45:58,507][INFO, (DispatcherHandler.java:38).run] BusinessHandler read msg from client :name:guowl sex:man age:30
[2017-02-22 15:45:58,514][INFO, (ClientInitHandler.java:27).channelRead] BusinessHandler read msg from server :name:guowl sex:man age:30
[2017-02-22 15:46:02,608][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-22 15:46:02,617][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:199)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:46)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:77)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:299)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:827)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:544)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:318)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.netty.Util.ByteObjConverter.ByteToObject(ByteObjConverter.java:37)
	at com.netty.test5.ser.PersonDecoder.decode(PersonDecoder.java:17)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeLast(ByteToMessageDecoder.java:283)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:194)
	... 9 more
[2017-02-22 15:50:02,899][WARN, (Slf4JLogger.java:151).warn] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-24 11:19:56,054][INFO, (ClassPathScanHandler.java:89).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 11:19:56,071][INFO, (ClassPathScanHandler.java:161).doScanPackageClassesByFile] scan source path:/D:/gitproj/demo/target/classes/com/springpri/dynamicLoadBean/demo3
[2017-02-24 11:24:04,786][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 11:24:04,803][INFO, (ClassPathScanHandler.java:126).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-24 14:05:49,477][ERROR, (TestContextManager.java:234).prepareTestInstance] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@1fe20588] to prepare test instance [com.springpri.dynamicLoadBean.demo4.DynamicBeanReaderTests@6ce139a4]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.springpri.dynamicLoadBean.demo4.DynamicBeanReaderTests': Unsatisfied dependency expressed through field 'dynamicBeanReader': No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:385)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1057)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 28 more
[2017-02-24 14:06:09,827][ERROR, (TestContextManager.java:234).prepareTestInstance] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@1fe20588] to prepare test instance [com.springpri.dynamicLoadBean.demo4.DynamicBeanReaderTests@6ce139a4]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.springpri.dynamicLoadBean.demo4.DynamicBeanReaderTests': Unsatisfied dependency expressed through field 'dynamicBeanReader': No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:385)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1057)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 28 more
[2017-02-24 14:08:22,142][ERROR, (TestContextManager.java:234).prepareTestInstance] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@f99f5e0] to prepare test instance [com.springpri.dynamicLoadBean.demo4.DynamicBeanReaderTests@6aa61224]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.springpri.dynamicLoadBean.demo4.DynamicBeanReaderTests': Unsatisfied dependency expressed through field 'dynamicBeanReader': No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:385)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1057)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 28 more
[2017-02-24 14:09:20,351][ERROR, (TestContextManager.java:234).prepareTestInstance] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@1fe20588] to prepare test instance [com.springpri.dynamicLoadBean.demo4.DynamicBeanReaderTests@6ce139a4]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.springpri.dynamicLoadBean.demo4.DynamicBeanReaderTests': Unsatisfied dependency expressed through field 'dynamicBeanReader': No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:385)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader] found for dependency [com.springpri.dynamicLoadBean.demo4.DynamicBeanReader]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1057)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 28 more
[2017-02-24 14:11:51,197][ERROR, (TestContextManager.java:234).prepareTestInstance] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@2133814f] to prepare test instance [com.springpri.dynamicLoadBean.demo4.DynamicBeanReaderTests@4c15e7fd]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.youi.common.bean.DynamicBeanReaderImpl] for bean with name 'dynamicBeanReader' defined in class path resource [com/springpri/dynamicLoadBean/demo4/applicationContext-test.xml]; nested exception is java.lang.ClassNotFoundException: org.youi.common.bean.DynamicBeanReaderImpl
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1357)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:597)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1450)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:980)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:108)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:251)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 25 more
Caused by: java.lang.ClassNotFoundException: org.youi.common.bean.DynamicBeanReaderImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:394)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1402)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1349)
	... 38 more
[2017-02-24 14:12:35,880][INFO, (DynamicBeanReaderImpl.java:38).loadBean] 初始化bean【dataSource1】耗时22毫秒。
[2017-02-24 14:13:41,655][INFO, (DynamicBeanReaderImpl.java:38).loadBean] 初始化bean【dataSource1】耗时23毫秒。
[2017-02-24 14:15:07,838][INFO, (DynamicBeanReaderImpl.java:38).loadBean] 初始化bean【dataSource1】耗时189毫秒。
[2017-02-24 14:17:24,287][INFO, (DynamicBeanReaderImpl.java:38).loadBean] 初始化bean【dataSource1】耗时20毫秒。
[2017-02-24 14:20:18,626][ERROR, (TestContextManager.java:234).prepareTestInstance] Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@4667ae56] to prepare test instance [com.springpri.dynamicLoadBean.demo4.DynamicBeanReaderTests@77cd7a0]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: Neither GenericXmlContextLoader nor AnnotationConfigContextLoader was able to load an ApplicationContext from [MergedContextConfiguration@1a968a59 testClass = DynamicBeanReaderTests, locations = '{}', classes = '{}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]].
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:263)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 25 more
[2017-02-24 14:20:48,268][INFO, (DynamicBeanReaderImpl.java:38).loadBean] 初始化bean【dataSource1】耗时17毫秒。
[2017-02-24 14:21:25,555][INFO, (DynamicBeanReaderImpl.java:38).loadBean] 初始化bean【dataSource1】耗时20毫秒。
[2017-02-24 14:26:01,449][INFO, (DynamicBeanReaderImpl.java:38).loadBean] 初始化bean【dataSource1】耗时21毫秒。
[2017-02-24 14:32:13,464][INFO, (DynamicBeanReaderImpl.java:38).loadBean] 初始化bean【dataSource1】耗时18毫秒。
[2017-02-24 14:38:28,613][INFO, (DynamicBeanReaderImpl.java:52).loadBean] 初始化bean【com.springpri.dynamicLoadBean.demo1.MagazineService】耗时1毫秒。
[2017-02-24 14:38:46,837][INFO, (DynamicBeanReaderImpl.java:52).loadBean] 初始化bean【com.springpri.dynamicLoadBean.demo1.MagazineService】耗时1毫秒。
[2017-02-24 14:39:41,243][INFO, (DynamicBeanReaderImpl.java:52).loadBean] 初始化bean【classpath:com.springpri.dynamicLoadBean.demo1.MagazineService】耗时1毫秒。
[2017-02-24 14:40:36,543][INFO, (DynamicBeanReaderImpl.java:52).loadBean] 初始化bean【classpath:com/springpri/dynamicLoadBean/demo1/MagazineService】耗时1毫秒。
[2017-02-24 14:43:09,296][INFO, (DynamicBeanReaderImpl.java:52).loadBean] 初始化bean【classpath:com/springpri/dynamicLoadBean/demo1/MagazineService】耗时3毫秒。
[2017-02-24 19:19:34,566][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 19:19:34,574][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-24 19:19:34,575][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-24 19:19:34,575][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$2.class
[2017-02-24 19:20:00,890][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 19:20:00,893][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-24 19:20:00,893][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-24 19:20:00,893][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$2.class
[2017-02-24 19:20:43,747][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 19:20:43,750][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-24 19:20:43,750][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-24 19:20:43,750][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$2.class
[2017-02-24 19:24:03,136][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 19:24:03,139][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-24 19:24:03,141][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-24 19:24:03,141][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$2.class
[2017-02-24 19:24:13,378][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 19:24:13,381][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-24 19:24:13,383][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-24 19:24:13,383][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$2.class
[2017-02-24 19:24:24,187][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 19:24:24,189][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-24 19:24:24,191][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-24 19:24:24,191][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$2.class
[2017-02-24 19:24:31,933][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 19:24:31,937][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-24 19:24:31,939][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-24 19:24:31,939][INFO, (ClassPathScanHandler.java:196).accept] exclude inner class with name:ClassPathScanHandler$2.class
[2017-02-24 19:25:32,736][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 19:25:32,739][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-24 19:25:32,741][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-24 19:29:31,516][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-24 19:29:31,520][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-24 19:29:31,522][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-25 08:41:04,329][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-25 08:41:04,371][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-25 08:41:04,373][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-25 08:48:33,650][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-25 08:48:33,653][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-25 08:48:33,655][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-25 08:50:31,034][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-25 08:50:31,037][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-25 08:50:31,039][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-25 09:02:30,355][INFO, (ClassPathScanHandler.java:56).getPackageAllClasses] 扫描file类型的class文件....
[2017-02-25 09:02:30,357][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassFinder$1.class
[2017-02-25 09:02:30,359][INFO, (ClassPathScanHandler.java:128).accept] exclude inner class with name:ClassPathScanHandler$1.class
[2017-02-25 14:42:20,695][INFO, (GlobalSettings.java:113).loadGlobalSettings] Trying to find Dozer configuration file: dozer.properties
[2017-02-25 14:42:20,913][WARN, (GlobalSettings.java:118).loadGlobalSettings] Dozer configuration file not found: dozer.properties.  Using defaults for all Dozer global properties.
[2017-02-25 14:42:21,042][INFO, (DozerInitializer.java:75).init] Initializing Dozer. Version: 5.5.0, Thread Name: main
[2017-02-25 14:42:22,154][INFO, (JMXPlatformImpl.java:66).register] Dozer JMX MBean [org.dozer.jmx:type=DozerStatisticsController] auto registered with the Platform MBean Server
[2017-02-25 14:42:22,156][INFO, (JMXPlatformImpl.java:66).register] Dozer JMX MBean [org.dozer.jmx:type=DozerAdminController] auto registered with the Platform MBean Server
[2017-02-25 14:42:22,159][INFO, (DozerBeanMapper.java:175).init] Initializing a new instance of dozer bean mapper.
